FROM debian:bookworm

RUN apt-get update && apt-get install -y --no-install-recommends \
    g++ \
    build-essential \
    libssl-dev \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /usr/src

EXPOSE 8080