name: iicpc

services:
  redpanda:
    image: redpandadata/redpanda:v23.3.14
    container_name: iicpc-redpanda
    command:
      - redpanda
      - start
      - --smp 2                          # Point E: pin to 1 CPU
      - --memory 400M
      - --reserve-memory 0M                 # Point E: hard memory cap
      - --overprovisioned
      - --kafka-addr PLAINTEXT://0.0.0.0:9092
      - --advertise-kafka-addr PLAINTEXT://redpanda:9092
    ports:
      - "9092:9092"
    networks:
      - iicpc-net
    mem_limit: 512m                       # Point E: Docker-level enforcement
    cpus: 2.0

  redis:
    image: redis:7-alpine
    container_name: iicpc-redis
    command: redis-server --appendonly yes --appendfsync everysec
    ports:
      - "6379:6379"
    networks:
      - iicpc-net
    volumes:
      - redis_data:/data

  postgres:
    image: postgres:15-alpine
    container_name: iicpc-postgres
    environment:
      POSTGRES_USER: iicpc
      POSTGRES_PASSWORD: iicpc_secret
      POSTGRES_DB: iicpc_db
    ports:
      - "5432:5432"
    networks:
      - iicpc-net
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U iicpc -d iicpc_db"]
      interval: 2s
      timeout: 2s
      retries: 10

  minio:
    image: minio/minio:latest
    container_name: iicpc-minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    networks:
      - iicpc-net
    volumes:
      - minio_data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 3s
      timeout: 3s
      retries: 5

  init-db:
    build:
      context: .
      dockerfile: Dockerfile.init-db
    container_name: iicpc-init-db
    command: -dir /migrations postgres "postgres://iicpc:iicpc_secret@postgres:5432/iicpc_db?sslmode=disable" up
    volumes:
      - ./migrations:/migrations
    networks:
      - iicpc-net
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  redis_data:
  postgres_data:
  minio_data:

networks:
  iicpc-net:
    driver: bridge