services:
  redis:
    image: redis:7-alpine
    command: redis-server --appendonly yes --appendfsync everysec
    networks:
      - iicpc-net
    volumes:
      - redis_data:/data
  worker-1:
    image: bot-fleet:v1
    command: ["-mode=worker", "-port=5001"]
    ports:
      - "5001:5001"
    environment:
      - KAFKA_BROKERS=redpanda:9092   # change this one line for any environment
      - REDIS_ADDR=redis:6379
    networks:
      - iicpc-net
      - sandbox-net
    mem_limit: 150m

  worker-2:
    image: bot-fleet:v1
    command: ["-mode=worker", "-port=5002"]
    ports:
      - "5002:5002"
    environment:
      - KAFKA_BROKERS=redpanda:9092   # change this one line for any environment
      - REDIS_ADDR=redis:6379
    networks:
      - iicpc-net
      - sandbox-net
    mem_limit: 150m


  worker-3:
    image: bot-fleet:v1
    command: ["-mode=worker", "-port=5003"]
    ports:
      - "5003:5003"
    environment:
      - KAFKA_BROKERS=redpanda:9092   # change this one line for any environment
      - REDIS_ADDR=redis:6379
    networks:
      - iicpc-net
      - sandbox-net
    mem_limit: 150m


  master:
    image: bot-fleet:v1
    command: ["-mode=master"]
    ports:
      - "4000:4000"
    networks:
      - iicpc-net
    environment:
      - KAFKA_BROKERS=redpanda:9092   # change this one line for any environment
      - WORKERS=worker-1:5001,worker-2:5002,worker-3:5003
      - REDIS_ADDR=redis:6379
      - DB_ADDR=postgres://iicpc:iicpc_secret@postgres:5432/iicpc_db?sslmode=disable
    mem_limit: 150m

volumes:
  redis_data:
  
networks:
  iicpc-net:
    driver: bridge
  sandbox-net:
    driver: bridge
    internal: true