apiVersion: batch/v1
kind: Job
metadata:
  name: iicpc-migration-job
  namespace: default
spec:
  template:
    spec:
      containers:
      - name: migration
        image: ghcr.io/pressly/goose:v3.20.0
        imagePullPolicy: IfNotPresent
        command:
        - sh
        - -c
        - |
          echo "Running Goose migrations..."
          goose -dir /migrations postgres "$DB_ADDR" up
        env:
        - name: DB_ADDR
          value: "postgres://iicpc:iicpc_secret@postgres:5432/iicpc_db?sslmode=disable"
        volumeMounts:
        - name: migration-volume
          mountPath: /migrations
      volumes:
      - name: migration-volume
        configMap:
          name: migrations-config
      restartPolicy: OnFailure
  backoffLimit: 5
