apiVersion: batch/v1
kind: Job
metadata:
  name: iicpc-migration-job
  namespace: default
spec:
  template:
    spec:
      containers:
      - name: migration
        image: iicpc-init-db:latest
        imagePullPolicy: IfNotPresent
        command:
        - /usr/local/bin/goose
        - -dir
        - /migrations
        - postgres
        - $(DB_ADDR)
        - up
        envFrom:
        - configMapRef:
            name: iicpc-config
        volumeMounts:
        - name: migration-volume
          mountPath: /migrations
      volumes:
      - name: migration-volume
        configMap:
          name: migrations-config
      restartPolicy: OnFailure
  backoffLimit: 5
